/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment2_SOFT2412;

import Assignment2_SOFT2412.data.CreditCard;
import Assignment2_SOFT2412.data.Database;
import Assignment2_SOFT2412.ui.StaffUI;
import Assignment2_SOFT2412.ui.UserUI;
import org.junit.jupiter.api.*;

import java.io.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Scanner;
import java.util.stream.Collectors;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    static Date defaultDate;

    PrintStream ps;
    ByteArrayOutputStream baos;

    Database db;
    Connection c;

//    @BeforeAll static void initDate() {
//        Calendar calendar = Calendar.getInstance();
//        calendar.set(2021, Calendar.NOVEMBER, 1, 0,0,0);
//        defaultDate = calendar.getTime();
//    }

    @BeforeEach
    void setup() throws IOException, InterruptedException {
// reset state of the test db
        ProcessBuilder pb = new ProcessBuilder("./db_create_test.sh");
        pb.directory(new File("assets"));

        Process p = pb.start();

        int exitVal = p.waitFor();
        assert exitVal == 0 : new BufferedReader(new InputStreamReader(p.getErrorStream()))
                .lines().collect(Collectors.joining("\n"));

//        connect to db
        c = Database.connectToSqlTest();
        db = new Database(c);

        //     change system.out to this custom printstream we create so that
//       we can test what gets printed out
        baos = new ByteArrayOutputStream();
        ps = new PrintStream(baos);

    }

    @AfterEach
    void cleanup() throws IOException, SQLException {
        baos.close();
        ps.close();

//        close db connection
        c.close();
    }

    private void userUiHelper(String input, String expectedOutput) {
        Scanner sc = new Scanner(new ByteArrayInputStream(input.getBytes()));
        UserUI u = new UserUI(db, sc, ps);
        u.setDefaultDate();
        u.start();
        assertEquals(expectedOutput, baos.toString());
        sc.close();
    }

    private void StaffUiHelper(String input, String expectedOutput) {
        Scanner sc = new Scanner(new ByteArrayInputStream(input.getBytes()));
        StaffUI s = new StaffUI(db, sc, ps);
        s.setDefaultDate();
        s.start();
        assertEquals(expectedOutput, baos.toString());
        sc.close();
    }

    @Test
    void quit() throws SQLException {
        String input =
                "quit\n";
        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Goodbye!\n";

        userUiHelper(input, expected);

    }

    @Test
    void showMovies() throws SQLException {
        String input =
                "list movies\n" +
                        "quit\n";
        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Here's a list of available movies:\n" +
                        "id                  movie               classification      synopsis            director            actor_cast          cinema              showing_date        booked_seats        seats_total         price               screen_size         \n" +
                        "\n" +
                        "3                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-03          1                   20                  $50.00              Gold                \n" +
                        "2                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-02          1                   50                  $20.00              Silver              \n" +
                        "1                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-01          1                   100                 $10.00              Bronze              \n" +
                        "5                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-03          1                   50                  $20.00              Silver              \n" +
                        "4                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-04          2                   100                 $10.00              Bronze              \n" +
                        "6                   yuri on ice         PG                  figure skating      Sayo Yamamoto       Suwabe, Junichi     hoits               2021-11-05          1                   20                  $50.00              Gold                \n" +
                        "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Goodbye!\n";

        userUiHelper(input, expected);
    }

    @Test
    void filterByCinema() throws SQLException {
        String input =
                "filter\n" +
                        "cinema\n" +
                        "hoits\n" +
                        "quit\n";

        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] What would you like to filter by? (screen size/price/classification/cinema): \n" +
                        "[guest] Which cinema would you like to filter by?\n" +
                        "id                  movie               classification      synopsis            director            actor_cast          cinema              showing_date        booked_seats        seats_total         price               screen_size         \n" +
                        "\n" +
                        "1                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-01          1                   100                 $10.00              Bronze              \n" +
                        "2                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-02          1                   50                  $20.00              Silver              \n" +
                        "3                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-03          1                   20                  $50.00              Gold                \n" +
                        "6                   yuri on ice         PG                  figure skating      Sayo Yamamoto       Suwabe, Junichi     hoits               2021-11-05          1                   20                  $50.00              Gold                \n" +
                        "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Goodbye!\n";

        userUiHelper(input, expected);
    }

    @Test
    void filterByClassification() throws SQLException {
        String input =
                "filter\n" +
                        "classification\n" +
                        "PG\n" +
                        "quit\n";

        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] What would you like to filter by? (screen size/price/classification/cinema): \n" +
                        "[guest] Which classification would you like to filter by? (g/pg/m/ma15+/r18+): \n" +
                        "id                  movie               classification      synopsis            director            actor_cast          cinema              showing_date        booked_seats        seats_total         price               screen_size         \n" +
                        "\n" +
                        "6                   yuri on ice         PG                  figure skating      Sayo Yamamoto       Suwabe, Junichi     hoits               2021-11-05          1                   20                  $50.00              Gold                \n" +
                        "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Goodbye!\n";

        userUiHelper(input, expected);
    }


    @Test
    void filterByPrice() throws SQLException {
        String input =
                "filter\n" +
                        "price\n" +
                        "20\n" +
                        "quit\n";

        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] What would you like to filter by? (screen size/price/classification/cinema): \n" +
                        "[guest] What is your maximum budget?\n" +
                        "id                  movie               classification      synopsis            director            actor_cast          cinema              showing_date        booked_seats        seats_total         price               screen_size         \n" +
                        "\n" +
                        "1                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-01          1                   100                 $10.00              Bronze              \n" +
                        "2                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-02          1                   50                  $20.00              Silver              \n" +
                        "4                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-04          2                   100                 $10.00              Bronze              \n" +
                        "5                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-03          1                   50                  $20.00              Silver              \n" +
                        "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Goodbye!\n";

        userUiHelper(input, expected);
    }

    @Test
    void filterByScreenSize() throws SQLException {
        String input =
                "filter\n" +
                        "screen size\n" +
                        "bronze\n" +
                        "quit\n";

        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] What would you like to filter by? (screen size/price/classification/cinema): \n" +
                        "[guest] Which screen size would you like to filter by? (bronze/silver/gold): \n" +
                        "id                  movie               classification      synopsis            director            actor_cast          cinema              showing_date        booked_seats        seats_total         price               screen_size         \n" +
                        "\n" +
                        "1                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-01          1                   100                 $10.00              Bronze              \n" +
                        "4                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-04          2                   100                 $10.00              Bronze              \n" +
                        "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Goodbye!\n";

        userUiHelper(input, expected);
    }

    @Test
    void userLogin() {
        String input =
                "login\n" +
                        "alex\n" +
                        "123\n" +
                        "quit\n";

        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Enter your username: \n" +
                        "[guest] Enter your password: \n" +
                        "[user alex] Welcome alex\n" +
                        "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
                        "[user alex] Goodbye!\n";

        userUiHelper(input, expected);

    }

    @Test
    void staffLogin() {
        String input =
                "login as staff\n" +
                        "shimiao\n" +
                        "123\n" +
                        "quit\n";

        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your staff account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[staff shimiao] Welcome shimiao\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Goodbye!\n";

        StaffUiHelper(input, expected);

    }

    @Test
    void managerLogin() {
        String input =
                "login as manager\n" +
                        "manager\n" +
                        "123\n" +
                        "quit\n";

        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your manager account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[manager manager] Welcome manager\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Goodbye!\n";

        StaffUiHelper(input, expected);

    }

    @Test
    void addMovieTest() {
        String input =
                "login as staff\n" +
                        "shimiao\n" +
                        "123\n" +
                        "add movies\n" +
                        "transformers\n" +
                        "M\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your staff account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[staff shimiao] Welcome shimiao\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Enter a name of movie: \n" +
                        "[staff shimiao] Enter the classification for this movie: \n" +
                        "[staff shimiao] Add successful!\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    @Test
    void addMovieWrongClassification() {
        String input =
                "login as staff\n" +
                        "shimiao\n" +
                        "123\n" +
                        "add movies\n" +
                        "transformers\n" +
                        "X\n" +
                        "quit\n";
        String expected = "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                "[staff] Enter your staff account name: \n" +
                "[staff] Enter your password: \n" +
                "[staff shimiao] Welcome shimiao\n" +
                "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                "[staff shimiao] Enter a name of movie: \n" +
                "[staff shimiao] Enter the classification for this movie: \n" +
                "[staff shimiao] Unable to add movie. Check the classification is correct.\n" +
                "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                "[staff shimiao] Goodbye!\n";
        StaffUiHelper(input, expected);

    }

    @Test
    void deleteMovieTest() {
        String input =
                "login as staff\n" +
                        "shimiao\n" +
                        "123\n" +
                        "delete movies\n" +
                        "your name\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your staff account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[staff shimiao] Welcome shimiao\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Enter the name of movie you want to delete: \n" +
                        "[staff shimiao] Delete successful!\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    @Test
    void modifyMovieExistTest() {
        String input =
                "login as staff\n" +
                        "shimiao\n" +
                        "123\n" +
                        "modify movies\n" +
                        "avatar\n" +
                        "M\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your staff account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[staff shimiao] Welcome shimiao\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Enter the name of movie: \n" +
                        "[staff shimiao] Enter the new classification you want to cover for this movie: \n" +
                        "[staff shimiao] Change successful!\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

//    commented out because this test case checks for filtering movies but that's already tested for in userUI ~Alex 01/11/21
//    @Test void checkSessionTest() {
//        String input =
//                "login as staff\n" +
//                        "shimiao\n" +
//                        "123\n" +
//                        "check sessions\n" +
//                        "cinema\n" +
//                        "hoits\n" +
//                        "quit\n";
//        String expected =
//                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
//                        "[staff] Enter your staff account name: \n" +
//                        "[staff] Enter your password: \n" +
//                        "[staff shimiao] Welcome shimiao\n" +
//                        "[staff shimiao] What would you like to do next? (add movies/add shows/delete movies/modify movies/check sessions/delete staff/add staff/quit): \n" +
//                        "[staff shimiao] Select a filter option:  (cinema/screen size/quit): \n" +
//                        "[staff shimiao] Enter the name of cinema you want to check: \n" +
//                        "id             movie          classification cinema         showing_date   booked_seats   seats_total    price          screen_size    \n" +
//                        "\n" +
//                        "1              your name      G              hoits          2021-10-01     1              100            $10.00         Bronze         \n" +
//                        "2              your name      G              hoits          2021-09-01     1              50             $20.00         Silver         \n" +
//                        "3              your name      G              hoits          2021-09-01     1              20             $50.00         Gold           \n" +
//                        "6              yuri on ice    PG             hoits          2021-03-01     1              20             $50.00         Gold           \n" +
//                        "8              avatar         M              hoits          2021-03-01     2              20             $50.00         Gold           \n" +
//                        "[staff shimiao] What would you like to do next? (add movies/add shows/delete movies/modify movies/check sessions/delete staff/add staff/quit): \n" +
//                        "[staff shimiao] Goodbye!\n";
//        StaffUiHelper(input, expected);
//
//    }

    @Test
    void addStaffTest() {
        String input =
                "login as manager\n" +
                        "manager\n" +
                        "123\n" +
                        "add staff\n" +
                        "staff\n" +
                        "123\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your manager account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[manager manager] Welcome manager\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Enter a staff account name you want to add: \n" +
                        "[manager manager] Enter the password you want to set: \n" +
                        "[manager manager] Add successful!\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    @Test
    void deleteStaffFailsTest() {
        String input =
                "login as manager\n" +
                        "manager\n" +
                        "123\n" +
                        "delete staff\n" +
                        "staff\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your manager account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[manager manager] Welcome manager\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Enter the staff account name you want to delete: \n" +
                        "[manager manager] No staff named staff exists!\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    @Test
    void deleteStaffTest() {
        String input =
                "login as manager\n" +
                        "manager\n" +
                        "123\n" +
                        "delete staff\n" +
                        "alex\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your manager account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[manager manager] Welcome manager\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Enter the staff account name you want to delete: \n" +
                        "[manager manager] Delete successful!\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    //    todo test that when we view movies again, we can see the tickets being booked (booked_seats should be increased)
    @Test
    void bookSession() {
        String input =
                "login\n" +
                        "alex\n" +
                        "123\n" +
                        "list movies\n" +
                        "book\n" +
//                movie id
                        "2\n" +
//                        child tickets
                        "1\n" +
//                        student tickets
                        "3\n" +
//                        adult tickets
                        "4\n" +
//                        senior tickets
                        "2\n" +
//                        front seat
                        "front\n" +
//                        payment
                        "gift card\n1234123412341236GC\n" +
//                        list movies check increase
                        "list movies\n" +
//                        quit app
                        "quit\n";

        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Enter your username: \n" +
                        "[guest] Enter your password: \n" +
                        "[user alex] Welcome alex\n" +
                        "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
                        "[user alex] Here's a list of available movies:\n" +
                        "id                  movie               classification      synopsis            director            actor_cast          cinema              showing_date        booked_seats        seats_total         price               screen_size         \n" +
                        "\n" +
                        "3                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-03          1                   20                  $50.00              Gold                \n" +
                        "2                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-02          1                   50                  $20.00              Silver              \n" +
                        "1                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-01          1                   100                 $10.00              Bronze              \n" +
                        "5                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-03          1                   50                  $20.00              Silver              \n" +
                        "4                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-04          2                   100                 $10.00              Bronze              \n" +
                        "6                   yuri on ice         PG                  figure skating      Sayo Yamamoto       Suwabe, Junichi     hoits               2021-11-05          1                   20                  $50.00              Gold                \n" +
                        "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
                        "[user alex] Which movie session would you like to watch (enter ID)?\n" +
                        "[user alex] Enter the number of child tickets you want to book:\n" +
                        "[user alex] Enter the number of student tickets you want to book:\n" +
                        "[user alex] Enter the number of adult tickets you want to book:\n" +
                        "[user alex] Enter the number of senior tickets you want to book:\n" +
                        "[user alex] Enter the seat area you want to choose: (front/middle/rear): \n" +
                        "[user alex] How would you like to pay?  (credit card/gift card/cancel): \n" +
                        "[user alex] Enter the serial number of the giftcard: \n" +
                        "[user alex] Booked successfully!\n" +
                        "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
                        "[user alex] Here's a list of available movies:\n" +
                        "id                  movie               classification      synopsis            director            actor_cast          cinema              showing_date        booked_seats        seats_total         price               screen_size         \n" +
                        "\n" +
                        "3                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-03          1                   20                  $50.00              Gold                \n" +
                        "2                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-02          11                  50                  $20.00              Silver              \n" +
                        "1                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    hoits               2021-11-01          1                   100                 $10.00              Bronze              \n" +
                        "5                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-03          1                   50                  $20.00              Silver              \n" +
                        "4                   your name           G                   body swapping       Makoto Shinkai      Ryunosuke Kamiki    evants              2021-11-04          2                   100                 $10.00              Bronze              \n" +
                        "6                   yuri on ice         PG                  figure skating      Sayo Yamamoto       Suwabe, Junichi     hoits               2021-11-05          1                   20                  $50.00              Gold                \n" +
                        "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
                        "[user alex] Goodbye!\n";

        userUiHelper(input, expected);
    }

    @Test
    void bookSessionCancellation() throws SQLException {
        String input =
                "login\n" +
                        "alex\n" +
                        "123\n" +
                        "book\n" +
//                movie id
                        "2\n" +
//                        child tickets
                        "1\n" +
//                        student tickets
                        "3\n" +
//                        adult tickets
                        "4\n" +
//                        senior tickets
                        "2\n" +
//                        seat area choose
                        "front\n" +
//                        cancel booking
                        "cancel\n" +
//                        quit app
                        "quit\n";

        String expected =
                "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
                        "[guest] Enter your username: \n" +
                        "[guest] Enter your password: \n" +
                        "[user alex] Welcome alex\n" +
                        "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
                        "[user alex] Which movie session would you like to watch (enter ID)?\n" +
                        "[user alex] Enter the number of child tickets you want to book:\n" +
                        "[user alex] Enter the number of student tickets you want to book:\n" +
                        "[user alex] Enter the number of adult tickets you want to book:\n" +
                        "[user alex] Enter the number of senior tickets you want to book:\n" +
                        "[user alex] Enter the seat area you want to choose: (front/middle/rear): \n" +
                        "[user alex] How would you like to pay?  (credit card/gift card/cancel): \n" +
                        "[user alex] Booking cancelled!\n" +
                        "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
                        "[user alex] Goodbye!\n";

        userUiHelper(input, expected);
    }

//    @Test
//    void GiftCardWithoutGC() {
//        String input =
//                "login\n" +
//                        "alex\n" +
//                        "123\n" +
//                        "book\n" +
////                movie id
//                        "2\n" +
////                        child tickets
//                        "1\n" +
////                        student tickets
//                        "3\n" +
////                        adult tickets
//                        "4\n" +
////                        senior tickets
//                        "2\n" +
////                        seat area choose
//                        "front\n" +
////                        cancel booking
//                        "gift card\n" +
//                        "1234123412341237\n" +
//                        "1234123412341234GC\n" +
//                        "1234123412341234GC\n" +
//                        "1234123412341238GC\n" +
//
//                        "quit\n";
//        String expected = "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
//                "[guest] Enter your username: \n" +
//                "[guest] Enter your password: \n" +
//                "[user alex] Welcome alex\n" +
//                "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
//                "[user alex] Which movie session would you like to watch (enter ID)?\n" +
//                "[user alex] Enter the number of child tickets you want to book:\n" +
//                "[user alex] Enter the number of student tickets you want to book:\n" +
//                "[user alex] Enter the number of adult tickets you want to book:\n" +
//                "[user alex] Enter the number of senior tickets you want to book:\n" +
//                "[user alex] Enter the seat area you want to choose: (front/middle/rear): \n" +
//                "[user alex] How would you like to pay?  (credit card/gift card/cancel): \n" +
//                "[user alex] Enter the serial number of the giftcard: \n" +
//                "[user alex] Invalid gift card number!\n" +
//                "[user alex] Enter the serial number of the giftcard: \n" +
//                "[user alex] Giftcard is not redeemable! Please try again.\n" +
//                "[user alex] Enter the serial number of the giftcard: \n" +
//                "[user alex] Internal error in system! Please try again.\n" +
//                "[user alex] Enter the serial number of the giftcard: \n" +
//                "[user alex] Booked successfully!\n" +
//                "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
//                "[user alex] Goodbye!\n";
//
//        userUiHelper(input, expected);
//    }

//    @Test
//    void bookWithGiftCard() {
//        String input =
//                "login\n" +
//                        "alex\n" +
//                        "123\n" +
//                        "book\n" +
////                movie id
//                        "2\n" +
////                        child tickets
//                        "1\n" +
////                        student tickets
//                        "3\n" +
////                        adult tickets
//                        "4\n" +
////                        senior tickets
//                        "2\n" +
////                        seat area choose
//                        "front\n" +
////                        cancel booking
//                        "gift card\n" +
//                        "1234123412341237GC\n" +
//                        "quit\n";
//        String expected = "[guest] What would you like to do next? (list movies/filter/book/register/login/quit): \n" +
//                "[guest] Enter your username: \n" +
//                "[guest] Enter your password: \n" +
//                "[user alex] Welcome alex\n" +
//                "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
//                "[user alex] Which movie session would you like to watch (enter ID)?\n" +
//                "[user alex] Enter the number of child tickets you want to book:\n" +
//                "[user alex] Enter the number of student tickets you want to book:\n" +
//                "[user alex] Enter the number of adult tickets you want to book:\n" +
//                "[user alex] Enter the number of senior tickets you want to book:\n" +
//                "[user alex] Enter the seat area you want to choose: (front/middle/rear): \n" +
//                "[user alex] How would you like to pay?  (credit card/gift card/cancel): \n" +
//                "[user alex] Enter the serial number of the giftcard: \n" +
//                "[user alex] Booked successfully!\n" +
//                "[user alex] What would you like to do next? (list movies/filter/book/view bookings/quit): \n" +
//                "[user alex] Goodbye!\n";
//
//        userUiHelper(input, expected);
//    }

    @Test
    void creditCardTest() {
//        assert thsi is a valid credit card
        assertTrue(CreditCard.isValid("40691", "Charles"));
        //        assert thsi is not a valid credit card (invalid number)
        assertFalse(CreditCard.isValid("42688", "Sergio"));
        //        assert thsi is not a valid credit card (correct number but invalid name)
        assertFalse(CreditCard.isValid("42689", "Sergoi"));

    }

    @Test
    void creditCardPayment() {
        String input = "42689\nSergio\nno\n";
        Scanner sc = new Scanner(new ByteArrayInputStream(input.getBytes()));

        UserUI u = new UserUI(db, sc, ps);
        assertTrue(u.payWithCreditCard());

        String expected = "[] Enter your credit card number: \n" +
                "[] Enter the name associated with the credit card: \n" +
                "[] Would you like to save your card number and details so you don't need to enter them again in future transactions? (yes/no): \n";
        assertEquals(expected, baos.toString());

        sc.close();
    }

    @Test
    void creditCardSaved() {
        String input = "yes\n";
        Scanner sc = new Scanner(new ByteArrayInputStream(input.getBytes()));

        UserUI u = new UserUI(db, sc, ps);
        u.setUser("adam");
        assertTrue(u.payWithCreditCard());

        String expected = "[] It looks like you have your credit card details saved from a previous transaction. Would you like to auto-fill these details? (yes/no): \n";
        assertEquals(expected, baos.toString());

        sc.close();
    }

    @Test
    void creditCardFailOnce() {
        String input = "42688\nSergio\n42689\nSergio\nno\n";
        Scanner sc = new Scanner(new ByteArrayInputStream(input.getBytes()));

        UserUI u = new UserUI(db, sc, ps);
        assertTrue(u.payWithCreditCard());

        String expected = "[] Enter your credit card number: \n" +
                "[] Enter the name associated with the credit card: \n" +
                "[] Invalid credit card details! Please try again.\n" +
                "[] Enter your credit card number: \n" +
                "[] Enter the name associated with the credit card: \n" +
                "[] Would you like to save your card number and details so you don't need to enter them again in future transactions? (yes/no): \n";
        assertEquals(expected, baos.toString());

        sc.close();
    }

    @Test void registerAccount() {
        String input = "basem\nabc\n";
        Scanner sc = new Scanner(new ByteArrayInputStream(input.getBytes()));

        UserUI u = new UserUI(db, sc, ps);
        assertTrue(u.registerAccount());

        String expected = "[] Enter a username: \n" +
                "[] Enter a password: \n" +
                "[] Registration complete!\n";
        assertEquals(expected, baos.toString());

        sc.close();
    }
    @Test void registerAccountFails() {
        String input = "alex\nabc\n";
        Scanner sc = new Scanner(new ByteArrayInputStream(input.getBytes()));

        UserUI u = new UserUI(db, sc, ps);
        assertFalse(u.registerAccount());

        String expected = "[] Enter a username: \n" +
                "[] Enter a password: \n" +
                "[] Failed to register! The username may already be taken.\n";
        assertEquals(expected, baos.toString());

        sc.close();
    }

    @Test void getBookings() {
        UserUI u = new UserUI(db, null, ps);
        u.setUser("alex");
        u.listBookings();

        String expected = "movie               classification      showing_date        seat_location       \n" +
                "\n" +
                "your name           G                   2021-11-01          front               \n" +
                "your name           G                   2021-11-02          middle              \n" +
                "your name           G                   2021-11-03          rear                \n";
        assertEquals(expected, baos.toString());

    }

    @Test void summaryMovieSessionTest() {
        String input =
                "login as staff\n" +
                        "shimiao\n" +
                        "123\n" +
                        "summary bookings\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your staff account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[staff shimiao] Welcome shimiao\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] A summary of the movie sessions has been saved to session-summary.txt\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    @Test void showUpcomingMovieTest() {
        String input =
                "login as staff\n" +
                        "shimiao\n" +
                        "123\n" +
                        "show upcoming movies\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your staff account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[staff shimiao] Welcome shimiao\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] A summary of the upcoming movies has been saved to upcoming-movie-summary.txt\n" +
                        "[staff shimiao] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff shimiao] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    @Test void cancelledBookingsSummaryTest() {
        String input =
                "login as manager\n" +
                        "manager\n" +
                        "123\n" +
                        "show canceled transaction\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your manager account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[manager manager] Welcome manager\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Here is the list of canceled transactions: \n" +
                        "id                            date_time                     account                       reason                        \n" +
                        "\n" +
                        "1                             2021-07-15 16:58:39           alex                          card payment failed           \n" +
                        "2                             2021-10-05 05:15:25           hans                          timeout                       \n" +
                        "3                             2021-11-01 15:21:09           hans                          user cancelled                \n" +
                        "File saved as canceled_bookings.txt\n" +
                        "[manager manager] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/show canceled transaction/add giftcard/delete staff/add staff/quit): \n" +
                        "[manager manager] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

    @Test
    void addGiftCardTest() throws SQLException {
        String input =
                "login as staff\n" +
                        "hans\n" +
                        "123\n" +
                        "add giftcard\n" +
                        "add manually\n" +
                        "1111111111111111\n" +
                        "quit\n";
        String expected =
                "[staff] What would you like to do next? (login as staff/login as manager/quit): \n" +
                        "[staff] Enter your staff account name: \n" +
                        "[staff] Enter your password: \n" +
                        "[staff hans] Welcome hans\n" +
                        "[staff hans] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff hans] Choose from the options to add gift card:  (add manually/import from txt file): \n" +
                        "[staff hans] Enter the card number(length must be 16) you want to add: \n" +
                        "[staff hans] Add successful!\n" +
                        "[staff hans] What would you like to do next? (add movies/add movie showing/add movie session/delete movies/modify movies/summary bookings/show upcoming movies/filter movies/add giftcard/quit): \n" +
                        "[staff hans] Goodbye!\n";
        StaffUiHelper(input, expected);
    }

}

