/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment2_SOFT2412;

import Assignment2_SOFT2412.data.Database;
import Assignment2_SOFT2412.ui.StaffUI;
import Assignment2_SOFT2412.ui.BaseUI;
import Assignment2_SOFT2412.ui.UserUI;

import java.io.Console;
import java.io.PrintStream;
import java.sql.*;
import java.util.Scanner;


public class App extends BaseUI {

    public App(Database db, Scanner s, PrintStream ps) {
        super(db, s, ps);
        super.mode = "startup";
    }

    public static void main(String[] args) throws Exception {
//
//        Console console = System.console();
//        if(console != null){
//            String s = String.valueOf(console.readPassword("Enter Password: "));
//            System.out.println(s);
//
//        } else {
//            System.out.println(console);
//        }


        Connection c=  Database.connectToSql();
        Database db = new Database(c);
        Scanner s = new Scanner(System.in);
        PrintStream ps = System.out;

        App a = new App(db,s,ps);
        a.start();

        c.close();
        s.close();
        ps.close();
    }

    @Override
    public void start() throws Exception {
        super.printFancy("Welcome to the best team cinema booking system!");

        String result = super.askOptions("Are you a cinema staff member?", "y", "n");

        switch (result) {
            case "y": {
                StaffUI u = new StaffUI(db, s, printStream);
                u.setDate();
                u.start();
                break;
            }
            case "n": {
                UserUI u = new UserUI(db,s,printStream);
//                just for testing, change this to 120 for 2 minutes
                u.setTimeout(5);
                u.setDate();
                u.start();
                break;
            }
        }
    }
}
