
BEGIN;

DROP TABLE IF EXISTS public.movie CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TABLE IF EXISTS public.cinema CASCADE;
DROP TABLE IF EXISTS public.screen_size CASCADE;
DROP TABLE IF EXISTS public.movie_showing CASCADE;
DROP TABLE IF EXISTS public.movie_session CASCADE;
DROP TABLE IF EXISTS public.booking CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.staffaccount CASCADE;
DROP TABLE IF EXISTS public.manageraccount CASCADE;
DROP VIEW IF EXISTS public.movie_session_v CASCADE;
DROP VIEW IF EXISTS public.booking_v CASCADE;

DROP TABLE IF EXISTS public.canceled_booking CASCADE;

-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
CREATE TABLE IF NOT EXISTS public.movie
(
    name text NOT NULL,
    classification text NOT NULL,
	synopsis text NULL,
	director text NULL,
	actor_cast text NULL,
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.classification
(
    description text NOT NULL,
    code text NOT NULL,
    PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.cinema
(
    cinema_name text NOT NULL,
    PRIMARY KEY (cinema_name)
);

CREATE TABLE IF NOT EXISTS public.movie_showing
(
    id serial NOT NULL,
    movie text NOT NULL,
    cinema text NOT NULL,
    available_dates daterange NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.account
(
    username text NOT NULL,
    password text NOT NULL,
	balance money NOT NULL,
	saved_card_number text NULL,
	saved_card_name text NULL,
    PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public.booking
(
    id serial NOT NULL,
    movie_session integer NOT NULL,
    seat_location text NOT NULL,
    account text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.canceled_booking
(
    id serial NOT NULL,
    date_time timestamp NOT NULL,
    account text DEFAULT 'anonymous',
    reason text NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.movie_session
(
    id serial NOT NULL,
    movie_showing integer NOT NULL,
    showing_date date NOT NULL,
    seats_total integer NOT NULL,
    price money NOT NULL,
    screen_size text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.staffaccount
(
	staffname text NOT NULL,
	password text NOT NULL,
	PRIMARY KEY (staffname)

);

CREATE TABLE IF NOT EXISTS public.manageraccount
(
	managername text NOT NULL,
	password text NOT NULL,
	PRIMARY KEY (managername)

);

ALTER TABLE IF EXISTS public.booking
    ADD FOREIGN KEY (account)
    REFERENCES public.account (username)
    NOT VALID;


ALTER TABLE IF EXISTS public.movie
    ADD FOREIGN KEY (classification)
    REFERENCES public.classification (code)
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD FOREIGN KEY (movie_session)
    REFERENCES public.movie_session (id)
    NOT VALID;


ALTER TABLE IF EXISTS public.movie_session
    ADD FOREIGN KEY (movie_showing)
    REFERENCES public.movie_showing (id)
    NOT VALID;


ALTER TABLE IF EXISTS public.movie_showing
    ADD FOREIGN KEY (movie)
    REFERENCES public.movie (name)
    NOT VALID;


ALTER TABLE IF EXISTS public.movie_showing
    ADD FOREIGN KEY (cinema)
    REFERENCES public.cinema (cinema_name)
    NOT VALID;

-- end of autogenerated

--Table that consists of giftcards


DROP TABLE IF EXISTS public.giftcards CASCADE;

CREATE TABLE IF NOT EXISTS public.giftcards
(
    serialNo CHAR(16) PRIMARY KEY, 
	redeemable INTEGER NOT NULL,
    balance money NOT NULL
);



	   

CREATE VIEW movie_session_v AS
SELECT movie_session.id, movie_showing.movie, movie.classification, movie.synopsis, movie.director, movie.actor_cast, movie_showing.cinema, movie_session.showing_date, 
((SELECT COUNT(*) FROM booking WHERE booking.movie_session=movie_session.id)) AS booked_seats, 
movie_session.seats_total, movie_session.price, movie_session.screen_size FROM movie_session 
JOIN movie_showing ON movie_session.movie_showing = movie_showing.id
JOIN movie ON movie.name = movie_showing.movie;


CREATE VIEW booking_v AS
SELECT movie_session_v.movie, movie_session_v.classification, movie_session_v.showing_date, booking.seat_location, booking.account FROM booking JOIN movie_session_v ON booking.movie_session = movie_session_v.id;

END;
